name = "StabilityNonlinearDiffusion"
uuid = "2b20ce42-f958-4640-814e-6651c116b2de"
authors = ["Olivier HÃ©not", "Maxime Payan"]
version = "1.0.0"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
ApproxFunFourier = "59844689-9c9d-51bf-9583-5b794ec66d30"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
RadiiPolynomial = "f2081a94-c849-46b6-8dc9-07bb90ed72a9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
ApproxFun = "0.13.28"
ApproxFunFourier = "0.3.31"
GLMakie = "0.11.5"
IntervalArithmetic = "0.22.28"
RadiiPolynomial = "0.8.20"
Revise = "3.7.3"
